# -*- coding: utf-8 -*-
"""Transfer Entropy Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-A7anNPlZH1bP2Uyt7CxlZGawFV0p0eI
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.api import VAR

!pip install pyinform

import pandas as pd

# Load CSV (first column = date)
df = pd.read_csv('/content/drive/MyDrive/data_clean.csv', index_col=0)

# Convert index to datetime
df.index = pd.to_datetime(df.index)

# Sort (important for time series)
df = df.sort_index()

data = df[['BTC_ret', 'SPX_ret', '^VIX', 'DX-Y.NYB', 'US10Y', 'BREAKEVEN']].copy()

# Dropping missing values
data = data.dropna()

data_diff = data.copy()

for col in ['^VIX', 'DX-Y.NYB', 'US10Y', 'BREAKEVEN']:
    data_diff[col] = data_diff[col].diff()

data_diff = data_diff.dropna()

import numpy as np
from pyinform.transferentropy import transfer_entropy

# Convert continuous data → discrete bins
def discretize(series, bins=5):
    return pd.qcut(series, bins, labels=False, duplicates='drop')

def compute_te(df, name):

    print("\n" + "="*50)
    print(f"TRANSFER ENTROPY: {name}")
    print("="*50)

    # Drop NA just in case
    df = df.dropna()

    # Discretize all columns
    df_disc = df.apply(discretize)

    results = {}

    macro_vars = ['SPX_ret', '^VIX', 'DX-Y.NYB', 'US10Y', 'BREAKEVEN']

    for var in macro_vars:
        try:
            te_value = transfer_entropy(
                df_disc[var].astype(int).values,
                df_disc['BTC_ret'].astype(int).values,
                k=1
            )
            results[var] = te_value
        except:
            results[var] = np.nan

    results = pd.Series(results).sort_values(ascending=False)

    print("\nInformation flow → BTC_ret:")
    print(results)

    return results

# FULL SAMPLE
te_full = compute_te(data_diff, "FULL SAMPLE")

# PRE-2020
pre_2020 = data_diff.loc[:'2020-01-01']
te_pre = compute_te(pre_2020, "PRE 2020")

# POST-2022
post_2022 = data_diff.loc['2022-01-01':]
te_post = compute_te(post_2022, "POST 2022")